apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-pvc
  labels:
    app: vaultwarden
spec:
  storageClassName: ""
  volumeName: vaultwarden-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
