apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
  labels:
    app: vaultwarden
type: Opaque
stringData:
  admin-token: ZWeB1cNJ+n5G1ErUDmHZh9zLoLdsfG93cybzdoqDOTsSfBWafuXQec2aAwcDH+13
