apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
  labels:
    app: nextcloud
type: Opaque
stringData:
  postgres-db: nextcloud_db
  postgres-user: nextcloud_user
  postgres-password: nextcloud_password
  nextcloud-admin-user: admin
  nextcloud-admin-password: admin_password
  trusted-domains: localhost
