apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  labels:
    app: pgadmin
type: Opaque
stringData:
  pgadmin-default-email: homelab@suuynyuy.com
  pgadmin-default-password: admin_password
